// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWL6WOhE6Amk-JH8N-Xdkwcjqd0DL7A9c',
    appId: '1:775995148373:web:9d645250ef6cff4f946cdc',
    messagingSenderId: '775995148373',
    projectId: 'freelancing-f0bd1',
    authDomain: 'freelancing-f0bd1.firebaseapp.com',
    databaseURL: 'https://freelancing-f0bd1-default-rtdb.firebaseio.com',
    storageBucket: 'freelancing-f0bd1.firebasestorage.app',
    measurementId: 'G-KDC2X91N1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79roDPRS1YSaA3cNE3pOsaQ2dLD2dPsA',
    appId: '1:775995148373:android:2368ce37a0a56c11946cdc',
    messagingSenderId: '775995148373',
    projectId: 'freelancing-f0bd1',
    databaseURL: 'https://freelancing-f0bd1-default-rtdb.firebaseio.com',
    storageBucket: 'freelancing-f0bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZg0KZlO-2LWywbiTqvp_adW86Vl4moY',
    appId: '1:775995148373:ios:4f80644d4e352ad8946cdc',
    messagingSenderId: '775995148373',
    projectId: 'freelancing-f0bd1',
    databaseURL: 'https://freelancing-f0bd1-default-rtdb.firebaseio.com',
    storageBucket: 'freelancing-f0bd1.firebasestorage.app',
    iosBundleId: 'com.example.stackedpractice01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVZg0KZlO-2LWywbiTqvp_adW86Vl4moY',
    appId: '1:775995148373:ios:4f80644d4e352ad8946cdc',
    messagingSenderId: '775995148373',
    projectId: 'freelancing-f0bd1',
    databaseURL: 'https://freelancing-f0bd1-default-rtdb.firebaseio.com',
    storageBucket: 'freelancing-f0bd1.firebasestorage.app',
    iosBundleId: 'com.example.stackedpractice01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWL6WOhE6Amk-JH8N-Xdkwcjqd0DL7A9c',
    appId: '1:775995148373:web:dc653274308fdbae946cdc',
    messagingSenderId: '775995148373',
    projectId: 'freelancing-f0bd1',
    authDomain: 'freelancing-f0bd1.firebaseapp.com',
    databaseURL: 'https://freelancing-f0bd1-default-rtdb.firebaseio.com',
    storageBucket: 'freelancing-f0bd1.firebasestorage.app',
    measurementId: 'G-5GVCLJJZPJ',
  );
}
